export const withdraw = [
  {
    id: 'slot_freespin',
    popypType: 'slot',
    canRedirect: true,
  },
  {
    id: 'evolution_balance',
    popypType: 'casino',
    canRedirect: false,
  },
  {
    id: 'ufo_freespin',
    popypType: 'ufo',
    canRedirect: false,
  },
];

export const casinoData = {
  id: 'evolution_balance',
  texts: {
    headertextKey: 'casinokey.1',
    contenttextKey: 'casinokey.2',
  },
  headerImageUrl: 'casino-big',
  popypType: 'CASINO',
  amount: 0,
  value: 0,
  withdrawTextkey1: 'casinokey.3',
  withdrawTextkey2: 'casinokey.4',
};

export const ufoData = {
  id: 'ufo_freespin',
  texts: {
    headertextKey: 'ufokey.1',
    contenttextKey: 'ufokey.2',
  },
  headerImageUrl: 'slot-big',
  popypType: 'UFO',
  amount: 0,
  value: 0,
  withdrawTextkey1: 'ufokey.3',
  withdrawTextkey2: 'ufokey.4',
};

export const slots = [
  {
    id: 'zodiac_wheel',
    imgurl: 'zodiac-wheel-0.15',
    text: 'ZODIAC WHEEL',
    slotType: 'EGT',
    state: false,
    redirectUrl: 'ZODIAC WHEEL',
    value: 0.15,
    amount: 0,
  },
  {
    id: '10_burning_heart',
    imgurl: '10-burning-heart',
    text: '10 BURNING HEART',
    slotType: 'EGT',
    state: false,
    redirectUrl: '10 BURNING HEART',
    value: 0.5,
    amount: 0,
  },
  {
    id: '20_dazzling_hot',
    imgurl: '20-dazzling-hot',
    text: '20 DAZZLING HOT',
    slotType: 'EGT',
    state: false,
    redirectUrl: '20 DAZZLING HOT',
    value: 1,
    amount: 0,
  },
  {
    id: 'shining_crown',
    imgurl: 'shining-crown-2',
    text: 'SHINING CROWN',
    slotType: 'EGT',
    state: false,
    redirectUrl: 'SHINING CROWN',
    value: 2,
    amount: 0,
  },
  {
    id: 'gates_of_olympus_0_2',
    imgurl: 'gates-of-lympus-0.2',
    text: 'GATES OF OLYMPUS',
    slotType: 'PRAGMATIC',
    state: false,
    redirectUrl: 'Gates%20of%20Olympus™',
    value: 0.2,
    amount: 0,
  },
  {
    id: 'sweet_bonanza_0_4',
    imgurl: 'sweet-bonaza-0.4',
    text: 'SWEET BONAZA',
    slotType: 'PRAGMATIC',
    state: false,
    redirectUrl: 'Sweet%20Bonanza',
    value: 0.4,
    amount: 0,
  },
  {
    id: 'sweet_bonanza_1_8',
    imgurl: 'sweet-bonaza-1.8',
    text: 'SWEET BONAZA',
    slotType: 'PRAGMATIC',
    state: false,
    redirectUrl: 'Sweet%20Bonanza',
    value: 1.8,
    amount: 0,
  },
  {
    id: 'gates_of_olympus_0_8',
    imgurl: 'gates-of-lympus-0.8',
    text: 'GATES OF OLYMPUS',
    slotType: 'PRAGMATIC',
    state: false,
    redirectUrl: 'Gates%20of%20Olympus™',
    value: 0.8,
    amount: 0,
  },
];
